### ISSUE TITLE
Non showing power

### ISSUE THREAD

**Issue by mccushjack** [flowstatedev/ciq-runpower#3]
the power field not showing while run (just dash line) eventhough the power from stryd is recognized

**Comment by flowstatedev** [comment]
Which watch do you have?

If you have a multisport-capable watch (Fenix, 735XT, 920XT, 935, 945, etc.) which natively supports power meters, please connect your Stryd as a **power meter**, as noted in the [documentation](https://github.com/flowstatedev/ciq-runpower/wiki/1.-Getting-Started). This will work even if your Stryd is already connected as a foot pod.

If you have a watch which does not natively support power meters, then enter the ANT+ ID of your Stryd in the app settings. This can be determined by pairing your Stryd as a foot pod and looking in the sensors menu.

Let me know if it still isn't working for you.

**Comment by mccushjack** [comment]
i'm using 735xt, and i added stryd as footpod and it didnt work, i connected as power and it worked (didn't notice that option before)

**Comment by flowstatedev** [comment]
Okay, glad it works for you!

I’m gonna go ahead and close this issue.
